### ISSUE TITLE
Generated YAML-like format is incompatible with YAML

### ISSUE THREAD

**Issue by jmatsu** [cookpad/license-tools-plugin#100]
Thanks for providing a great plugin :)

Let me report a bug while parsing a license yaml file.
This plugin failed to load a license.yml like below if a library name includes a column with spaces, i.e. " : "

<img width="300" src="https://user-images.githubusercontent.com/4340693/47124694-3503ed80-d2ba-11e8-9b9c-d4e449bd1b71.jpg" >

It seems this plugin generates YAML-like text by manual but it's not a valid YAML. 

https://github.com/cookpad/license-tools-plugin/blob/ae78c7fad7e3af227901b53ff971eaacd70df4ac/plugin/src/main/groovy/com/cookpad/android/licensetools/LicenseToolsPlugin.groovy#L202

Thanks.

**Comment by ellenhp** [comment]
In case it isn't obvious for newcomers to this plugin (it wasn't obvious to me), you can just manually edit the generated "yaml" file so that it's actually parseable as yaml. `gradle checkLicenses` will then pass, and running `gradle updateLicenses` after that won't destroy your edit. That turned what I thought was a blocker into a very minor inconvenience.

**Comment by k4zy** [comment]
We are going to archive this repository.
Please migrate kazyApp/LicenseToolsPlugin
I will fix this problem kazyApp/LicenseToolsPlugin#3
