### ISSUE TITLE
Only works for multi-project builds?

### ISSUE THREAD

**Issue by steveperrin** [cookpad/license-tools-plugin#83]
The LicenseToolsPlugin.resolveProjectDependencies() method appears to only check for dependencies in subprojects:

https://github.com/cookpad/license-tools-plugin/blob/52d7499cc59dfc5b29ef4bbaa4f0865bbffeda93/plugin/src/main/groovy/com/cookpad/android/licensetools/LicenseToolsPlugin.groovy#L289

Shouldn't this method also include the rootProject dependencies?  The rootProject may have it's own  dependencies in addition to those in subprojects.  Also, if the rootProject dependencies aren't included, the plugin will only show licenses for multi-project builds, and won't work for projects that only have a single build.gradle file.

**Comment by KazuCocoa** [comment]
This plugin resolves dependencies in https://github.com/cookpad/license-tools-plugin/blob/master/settings.gradle .

```groovy
println(project.rootProject) // => root project 'license-tools-plugin'
println(project.rootProject.subprojects) // => [project ':example', project ':example-dep', project ':plugin']
```

Since in our usecase, https://github.com/cookpad/license-tools-plugin/blob/master/example/build.gradle#L86 , for example, manages dependencies which will be released. So, resovling `settings.gradle` is satisfied with the use case.
